### PR TITLE
show previous view of single choice questions when pressed back key

### PR DESCRIPTION
**Pull request by SanBal**

### CODE REVIEW

**Comment by SanBal** [comment]
@AndreiD  could you look at the pull request pls :) ?

**Comment by AndreiD** [comment]
Yes sure. As soon as I find little free time.

**Comment by SanBal** [comment]
We want to use your library in our important project. 
The problem is that our deadline is very soon. 
So it would be nice if you could look at the pull request preferably 
within the next two days and if it's acceptable merging it. Thanks :).

**Comment by CrandellWS** [comment]
@SanBal you do not have wait you can use your source now. 

If you mean "REVIEW YOUR PULL REQUEST", I would not do it that way

**Comment by CrandellWS** [comment]
I would prefer to get the data from the Answers and use that info in the onActivityCreated to set if the checkbox is checked or not. This way if the activity gets recreated I still can access the data to determine which was the selected answer and set the button correctly...

**Comment by AndreiD** [comment]
listen people...  like it's said in the description.
"Simplest way is to Fork this project and style, add, modify who you like."

Currently I have some things with priority on my mind and I'm a little behind android development.

Please fork it//download it, and customize it like you wanna. 

giving me 2 days deadline it's the best joke I heard today :)

**Pull request closed without merging**
